# Deploy the website

name: Deploy

on:
  # Triggers on published releases
  release:
    types: [ published ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ftp:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ftp-action
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          forceSsl: false
          localDir: .
          remoteDir: .
